config/routes.rb
Rails.application.routes.draw do
  get 'sales_forecasts/download'
  
  get 'keyword/search'
  
  post 'keyword/search'

  get 'admin/index'
  
  post 'admin/set_database_user'

  get 'login/index'
  
  post 'login/auth'
  
  post 'login/logout'
  
  resources :sales_forecasts

  resources :certainties

  resources :budgets

  resources :statuses

  resources :areas

  resources :segments

  resources :service_centers

  
  root to: 'sales_forecasts#index'
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:name, :color)
    end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_form.html.erb
<%= form_for(@status) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.color_field :color %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>状態編集</h1>

<%= render 'form' %>

<%= link_to '詳細', @status %> |
<%= link_to '戻る', statuses_path %>

app/views/statuses/index.html.erb
<h1>状態一覧</h1>

<table class="table">
  <thead>
    <tr>
      <th>状態</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @statuses.each do |status| %>
      <tr>
        <td style="color: <%= status.color %>"><%= status.name %></td>
        <td>
        	<%= link_to '詳細', status, class: :forecast_control %>
        	<%= link_to '編集', edit_status_path(status), class: :forecasst_control %>
        	<%= link_to '削除', status, method: :delete, data: { confirm: '削除しますか?' }, class: :forecast_control %>
       	</td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新規作成', new_status_path %>

app/views/statuses/new.html.erb
<h1>状態作成</h1>

<%= render 'form' %>

<%= link_to '戻る', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-bordered forecast_show_table">
	<tr>
		<td class="show_caption">状態</td>
		<td class="show_data"><%= @status.name %></td>
	</tr>
	<tr>
		<td class="show_caption">表示色</td>
		<td class="show_data"><span style="color: <%= @status.color %>; background-color: <%= @status.color %>"><%= @status.color %></td>
			
	</tr>			
</table>

<%= link_to '編集', edit_status_path(@status) %> |
<%= link_to '戻る', statuses_path %>