config/routes.rb
Rails.application.routes.draw do
  get 'sales_forecasts/download'
  
  get 'keyword/search'
  
  post 'keyword/search'

  get 'admin/index'
  
  post 'admin/set_database_user'

  get 'login/index'
  
  post 'login/auth'
  
  post 'login/logout'
  
  resources :sales_forecasts

  resources :certainties

  resources :budgets

  resources :statuses

  resources :areas

  resources :segments

  resources :service_centers

  
  root to: 'sales_forecasts#index'
end

app/models/segment.rb
class Segment < ActiveRecord::Base
  has_many :sales_forecasts
  
  validates :name,
  presence: true
end

app/controllers/segments_controller.rb
class SegmentsController < ApplicationController
  before_action :set_segment, only: [:show, :edit, :update, :destroy]

  # GET /segments
  # GET /segments.json
  def index
    @segments = Segment.all
  end

  # GET /segments/1
  # GET /segments/1.json
  def show
  end

  # GET /segments/new
  def new
    @segment = Segment.new
  end

  # GET /segments/1/edit
  def edit
  end

  # POST /segments
  # POST /segments.json
  def create
    @segment = Segment.new(segment_params)

    respond_to do |format|
      if @segment.save
        format.html { redirect_to @segment, notice: 'Segment was successfully created.' }
        format.json { render :show, status: :created, location: @segment }
      else
        format.html { render :new }
        format.json { render json: @segment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /segments/1
  # PATCH/PUT /segments/1.json
  def update
    respond_to do |format|
      if @segment.update(segment_params)
        format.html { redirect_to @segment, notice: 'Segment was successfully updated.' }
        format.json { render :show, status: :ok, location: @segment }
      else
        format.html { render :edit }
        format.json { render json: @segment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /segments/1
  # DELETE /segments/1.json
  def destroy
    @segment.destroy
    respond_to do |format|
      format.html { redirect_to segments_url, notice: 'Segment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_segment
      @segment = Segment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def segment_params
      params.require(:segment).permit(:name)
    end
end

app/helpers/segments_helper.rb
module SegmentsHelper
end

app/views/segments/_form.html.erb
<%= form_for(@segment) do |f| %>
  <% if @segment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@segment.errors.count, "error") %> prohibited this segment from being saved:</h2>

      <ul>
      <% @segment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/segments/edit.html.erb
<h1>客層編集</h1>

<%= render 'form' %>

<%= link_to '詳細', @segment %> |
<%= link_to '戻る', segments_path %>

app/views/segments/index.html.erb
<h1>客層一覧</h1>

<table class="table">
  <thead>
    <tr>
      <th>客層</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @segments.each do |segment| %>
      <tr>
        <td><%= segment.name %></td>
        <td>
        	<%= link_to '詳細', segment, class: :forecast_control %>
        	<%= link_to '編集', edit_segment_path(segment), class: :forecast_control %>
        	<%= link_to '削除', segment, method: :delete, data: { confirm: '削除しますか?' }, class: :forecast_contorl %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新規作成', new_segment_path %>

app/views/segments/new.html.erb
<h1>客層作成</h1>

<%= render 'form' %>

<%= link_to '戻る', segments_path %>

app/views/segments/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-bordered forecast_show_table">
	<tr>
		<td class="show_caption">客層</td>
		<td class="show_data"><%= @segment.name %></td>
	</tr>
</table>

<%= link_to '編集', edit_segment_path(@segment) %> |
<%= link_to '戻る', segments_path %>