config/routes.rb
Rails.application.routes.draw do
  get 'sales_forecasts/download'
  
  get 'keyword/search'
  
  post 'keyword/search'

  get 'admin/index'
  
  post 'admin/set_database_user'

  get 'login/index'
  
  post 'login/auth'
  
  post 'login/logout'
  
  resources :sales_forecasts

  resources :certainties

  resources :budgets

  resources :statuses

  resources :areas

  resources :segments

  resources :service_centers

  
  root to: 'sales_forecasts#index'
end

app/models/certainty.rb
class Certainty < ActiveRecord::Base
  has_many :sales_forecasts
  
  validates :name,
  presence: true,
  uniqueness: true,
  numericality: { only_integer: true, less_than_or_equal_to: 100 }
end

app/controllers/certainties_controller.rb
class CertaintiesController < ApplicationController
  before_action :set_certainty, only: [:show, :edit, :update, :destroy]

  # GET /certainties
  # GET /certainties.json
  def index
    @certainties = Certainty.all
  end

  # GET /certainties/1
  # GET /certainties/1.json
  def show
  end

  # GET /certainties/new
  def new
    @certainty = Certainty.new
  end

  # GET /certainties/1/edit
  def edit
  end

  # POST /certainties
  # POST /certainties.json
  def create
    @certainty = Certainty.new(certainty_params)

    respond_to do |format|
      if @certainty.save
        format.html { redirect_to @certainty, notice: 'Certainty was successfully created.' }
        format.json { render :show, status: :created, location: @certainty }
      else
        format.html { render :new }
        format.json { render json: @certainty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /certainties/1
  # PATCH/PUT /certainties/1.json
  def update
    respond_to do |format|
      if @certainty.update(certainty_params)
        format.html { redirect_to @certainty, notice: 'Certainty was successfully updated.' }
        format.json { render :show, status: :ok, location: @certainty }
      else
        format.html { render :edit }
        format.json { render json: @certainty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /certainties/1
  # DELETE /certainties/1.json
  def destroy
    @certainty.destroy
    respond_to do |format|
      format.html { redirect_to certainties_url, notice: 'Certainty was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_certainty
      @certainty = Certainty.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def certainty_params
      params.require(:certainty).permit(:name)
    end
end

app/helpers/certainties_helper.rb
module CertaintiesHelper
end

app/views/certainties/_form.html.erb
<%= form_for(@certainty) do |f| %>
  <% if @certainty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@certainty.errors.count, "error") %> prohibited this certainty from being saved:</h2>

      <ul>
      <% @certainty.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.number_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/certainties/edit.html.erb
<h1>確度編集</h1>

<%= render 'form' %>

<%= link_to '詳細', @certainty %> |
<%= link_to '戻る', certainties_path %>

app/views/certainties/index.html.erb
<h1>確度一覧</h1>

<table class="table">
  <thead>
    <tr>
      <th>確度</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @certainties.each do |certainty| %>
      <tr>
        <td><%= certainty.name %></td>
        <td>
        	<%= link_to '詳細', certainty, class: :forecast_control %>
        	<%= link_to '編集', edit_certainty_path(certainty), class: :forecast_control %>
        	<%= link_to '削除', certainty, method: :delete, data: { confirm: '削除しますか?' }, class: :forecast_control %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新規作成', new_certainty_path %>

app/views/certainties/new.html.erb
<h1>確度作成</h1>

<%= render 'form' %>

<%= link_to '戻る', certainties_path %>

app/views/certainties/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-bordered forecast_show_table">
	<tr>
		<td class="show_caption">確度</td>
		<td class="show_data"><%= @certainty.name %>
</table>

<%= link_to '編集', edit_certainty_path(@certainty) %> |
<%= link_to '戻る', certainties_path %>