config/routes.rb
Rails.application.routes.draw do
  get 'sales_forecasts/download'
  
  get 'keyword/search'
  
  post 'keyword/search'

  get 'admin/index'
  
  post 'admin/set_database_user'

  get 'login/index'
  
  post 'login/auth'
  
  post 'login/logout'
  
  resources :sales_forecasts

  resources :certainties

  resources :budgets

  resources :statuses

  resources :areas

  resources :segments

  resources :service_centers

  
  root to: 'sales_forecasts#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Forecast</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta content="width=device-width, initial-scale=1" name="viewport">
</head>
<body>
	<nav class="navbar navbar-inverse" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<%= link_to 'FORECAST', sales_forecasts_path, class: "navbar-brand" %>
			</div>
			<% if @usr %>
				<div class="collapse navbar-collapse">
					<%= form_tag({controller: :login, action: :logout}, class: "navbar-form navbar-right", role: "form") do %>
						<%= submit_tag 'Sign out', class: "btn btn-link" %>
					<% end %>
					<ul class="nav navbar-nav navbar-right">
						<li class="dropdown">
							<a href="#" id="settings_drop" role="button" class="dropdown-toggle" data-toggle="dropdown">Settings<span class="caret"></span></a>
							<ul class="dropdown-menu" role="menu" aria-labelledby="settings_drop">
								<% if $sc_switch %>
								<li role="presentation"><%= link_to 'SC', service_centers_path, role: "menu_item" %></li>
								<% end %>
								<li role="presentation"><%= link_to '客層', segments_path, role: "menuitem" %></li>
								<li role="presentation"><%= link_to '状態', statuses_path, role: "menuitem" %></li>
								<li role="presentation"><%= link_to '地域', areas_path, role: "menuitem" %></li>
								<li role="presentation"><%= link_to '予算', budgets_path, role: "menuitem" %></li>
								<li role="presentation"><%= link_to '確度', certainties_path, role: "menuitem" %></li>
							</ul>
						</li>
					</ul>
					<%= form_tag({controller: :keyword, action: :search}, class: "navbar-form navbar-right", role: "form") do %>
						<div class="form-group">
							<%= text_field_tag :keywd, '', class: "form-control", placeholder: "Keyword" %>
						</div>
						<%= hidden_field_tag :show_all, @show_all  %>
						<%= submit_tag 'Search', class: "btn btn-default" %>
					<% end %>
				</div><!--/.nav-collapse -->
			<% end %>
		</div>
	</nav>
	<div class="container">
		<%= yield %>
	</div>
</body>
</html>